### ISSUE TITLE
Node Webkit and PouchDB on Windows

### ISSUE THREAD

**Issue by sumit0k** [nolanlawson/pouchdb-nw-hello-world#1]
I am trying to use PouchDB on Node Webkit and it requires LevelDown. Windows is not able to compile it, therefore I am trying to use sqldown as an adapter which works outside the NodeWebkit but not inside it. Please suggest.

**Comment by nolanlawson** [comment]
From what I've heard, LevelDown just does not work well on Windows. My suggestion would be to use IndexedDB/WebSQL, or if you absolutely need to have it run in a Node process, then SqlDown with SQLite (this is slow, however).

**Comment by sumit0k** [comment]
SqlDown with SQLlite is not working in NodeWebkit, it works outside the node-webkit. Is there anything that could be used similar to Express-PouchDB server with Express App in NW.js?

**Comment by nolanlawson** [comment]
That's odd, most likely the reason it's not working is because you haven't npm installed sqlite3 and sqldown. If you want some help, I recommend running:

```
npm install -g pouchdb-server
pouchdb-server --help
```

This will print helpful info to get pouchdb-server running with sqlite. It worked pretty easily for me and I have heard from Windows developers that it worked for them.

Alternatively, any of the *down implementations should work in theory: http://pouchdb.com/adapters.html#pouchdb_in_node_js

**Comment by nolanlawson** [comment]
There is also `leveldown-prebuilt` as described here: http://pouchdb.com/errors.html#windows_leveldown

**Comment by sumit0k** [comment]
yeah tried it, but shows not valid 32 application

**Comment by nolanlawson** [comment]
There's also `level-11` which supposedly works well on Node 0.11.

Since this is a leveldown issue, you might have more luck looking inside that project: https://github.com/rvagg/node-leveldown/search?q=windows&type=Issues&utf8=%E2%9C%93. But again, you can probably save yourself a lot of headache if you just use IndexedDB/WebSQL (heck, IndexedDB uses LevelDB under the hood in Chromium anyway :))

**Comment by sumit0k** [comment]
<code>npm install -g pouchdb-server</code>
This installed all components but LevelDown and working on level-11 solution, hope this works.

 IndexedDB/WebSQL  are client side solutions, I am trying to create a PouchDB server integrated within my NW.js project.

**Comment by nolanlawson** [comment]
ahhh, gotcha. I misunderstood. Then yeah, pouchdb-server with level-11 sounds good. If you get stuck, try the ##leveldb room in Freenode IRC. I also found these instructions for building `leveldown` on Windows: https://github.com/TooTallNate/node-gyp#installation
